import { ColorSchemeScript, MantineProvider } from '@mantine/core'
import type { Metadata } from 'next'

import './globals.css'
import '@mantine/charts/styles.css'
import '@mantine/core/styles.css'
import '@mantine/dates/styles.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: any) {
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript defaultColorScheme="dark" />
			</head>
			<body>
				<MantineProvider defaultColorScheme="dark">{children}</MantineProvider>
			</body>
		</html>
	)
}
