import Providers from '@/providers'
import { ColorSchemeScript, MantineProvider } from '@mantine/core'
import type { Metadata } from 'next'

import '@mantine/charts/styles.css'
import '@mantine/core/styles.css'
import '@mantine/dates/styles.css'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: any) {
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript />
			</head>
			<body className="scroll-smooths select-none overflow-x-hidden">
				<MantineProvider>
					<Providers>{children}</Providers>
				</MantineProvider>
			</body>
		</html>
	)
}
